### PR TITLE
Replace pelletier/go-toml with BurntSushi/toml

### PR DESCRIPTION
**Pull request by modulo11**
## Summary

Fixes https://github.com/paketo-buildpacks/libpak/issues/146 and aligns the libraries for toml parsing along buildpacks and paketo. Changes are rather small but should be tested extensively.

One big difference, that leads to the changes in `layer_test.go`, is that the library [ignores](https://github.com/BurntSushi/toml/blob/74c008f3d2dcb9c295248aada067301a0d810932/encode.go#L495-L497) `nil` values entirely when encoding data.

## Use Cases

- Use `github.com/BurntSushi/toml` instead of `github.com/pelletier/go-toml`

## Checklist

* [X] I have viewed, signed, and submitted the Contributor License Agreement.
* [X] I have linked issue(s) that this PR should close using keywords or the Github UI (See [docs](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue))
* [X] I have added an integration test, if necessary.
* [X] I have reviewed the [styleguide](https://github.com/paketo-buildpacks/community/blob/main/STYLEGUIDE.md) for guidance on my code quality.
* [X] I'm happy with the commit history on this PR (I have rebased/squashed as needed).

### CODE REVIEW

**Review by anthonydahanne — COMMENTED** [review]
That looks good to me. Maybe I'd add a unit test for `Marshall` that would marshall a toml file and unmarshall it to check everything went well.

But you already exercise this method, so not even sure it's worth it.Up to you.

**Comment by dmikusa** [comment]
This looks good to me as well. I did some testing and didn't notice anything out of the ordinary. I also added the test that @anthonydahanne suggested.

**Review by dmikusa — APPROVED** [review]

**Comment by anthonydahanne** [comment]
> Wondering what others think about making this change in v1, or if we should hold this for v2 as well.
to me that could go in immediately; consumers won't notice the difference since those are internal changes

**Comment by dmikusa** [comment]
Yes, that was my thought as well @anthonydahanne

**Review by anthonydahanne — APPROVED** [review]

**Comment by anthonydahanne** [comment]
Good to go!

**Pull request merged**
