### PR TITLE
Automatically add `deprecation_date` field to buildpack dependencies if requested

### PR DESCRIPTION
**Pull request by pbusko**
## Summary

Automatically populate `deprecation_date` for dependencies

## Use Cases

This change adds the `--eol-id` flag to the `update-buildpack-dependencies` cmd. When the flag is set, the product the EOL date is looked up for a product (the `--eol-id` flag), formatted and added to the `deprecation_date` field.

## Checklist

* [X] I have viewed, signed, and submitted the Contributor License Agreement.
* [X] I have linked issue(s) that this PR should close using keywords or the Github UI (See [docs](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue))
* [X] I have added an integration test, if necessary.
* [X] I have reviewed the [styleguide](https://github.com/paketo-buildpacks/community/blob/main/STYLEGUIDE.md) for guidance on my code quality.
* [X] I'm happy with the commit history on this PR (I have rebased/squashed as needed).

### CODE REVIEW

**Comment by dmikusa** [comment]
I don't feel like we should pull in a dependency on github.com/kobayashi/eol. It's a 0.1.0 release and hasn't been updated in over a year (last commit). It doesn't show strong signs of life. If I'm missing something there please let me know.

It may be a little more work, but there are only three API calls for the API itself, https://endoflife.date/docs/api. Do you have any objections to just making HTTP calls directly to the API? You could add a client under the `internal` package, so we don't need to worry about exporting that as public, it'll be just for the library.

**Comment by pbusko** [comment]
> It's a 0.1.0 release and hasn't been updated in over a year (last commit)

good point, I've moved the implementation to the internal package

**Review by c0d1ngm0nk3y — APPROVED** [review]
Some smaller comments...

**Comment by c0d1ngm0nk3y** [comment]
@dmikusa We call the API directly instead of using the additional dependency like you proposed in [this comment.](https://github.com/paketo-buildpacks/libpak/pull/345#issuecomment-2153014136) Maybe you can have another look.

**Comment by pbusko** [comment]
@dmikusa is there anything else blocking the PR from being merged?

**Review by dmikusa — APPROVED** [review]

**Pull request merged**
